theme: jekyll-theme-minimal
title: Fuji Money  
description: Fuji Moneyの紹介サイトです
github:
  is_project_page: false
{% for post in paginator.posts %}
<a href ="{{post.url}}">{{post.title}}</a>
{% endfor %}
