theme: jekyll-theme-minimal
title: 富士コイン
description: 富士コインの紹介サイトです
github:
  is_project_page: false

text:
[活動内容](./activities)  
[実施要項](./guide)  
[コインについて](./coin)  
[関係組織](./stakeholders)  
[アカウントの扱い方](./acount)  
